DROP TABLE BOOK;
drop sequence book_seq;
CREATE TABLE BOOK(
	BOOK_ID			NUMBER,
	CONCERT_ID		NUMBER			NOT NULL,
	MEMBER_ID		VARCHAR2(20)	NOT NULL,
	BOOK_ETICKET	VARCHAR2(20)	NOT NULL,
	BOOK_AMOUNT		NUMBER			NOT NULL,
	CARD_ID			NUMBER			NOT NULL,
	BOOK_DATE		DATE			NOT NULL,
	PRIMARY KEY(BOOK_ID),
	FOREIGN KEY(CONCERT_ID) REFERENCES CONCERT,
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER,
	FOREIGN KEY(CARD_ID) REFERENCES CARD
);
create sequence book_seq increment by 1 start with 1;
SELECT * FROM BOOK;

DELETE * FROM BOOK;

INSERT INTO BOOK VALUES(book_seq.nextval, 1, 'abc123@mfe.com', 'e123456789', 1, 1, SYSDATE);