CREATE TABLE CARD(
	CARD_ID		NUMBER,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	CARD_MMYY	NUMBER	NOT NULL,
	CARD_CVV	NUMBER	NOT NULL,
	PRIMARY KEY(CARD_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER
);

create sequence card_seq increment by 1 start with 1;
SELECT * FROM CARD;
DELETE FROM CARD;

INSERT INTO CARD VALUES(card_seq.nextval, 'abc123@mfe.com', 0628, 123);