CREATE TABLE CARD(
	CARD_ID		NUMBER,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	CARD_MMYY	NUMBER	NOT NULL,
	CARD_CVV	NUMBER	NOT NULL,
	CONSTRAINT	PRIMARY KEY(CARD_ID),
	CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);


SELECT * FROM CARD;
DELETE FROM CARD;

INSERT(CARD_ID, MEMBER_ID, CARD_MMYY, CARD_CVV) 
INTO CARD 
VALUES(1, 'TEST_ID', 0628, 123);