CREATE TABLE CHAT(
	CHAH_LOG_ID			NUMBER,
	MEMBER_ID			NUMBER	NOT NULL,
	CHAR_LOG_ANSWER		VARCHAR2(100),
	CHAH_LOG_CONTENT	VARCHAR2(100)	NOT NULL,
	CHAR_LOG_DATE		DATE	NOT NULL,
	CONSTRAINT	PRIMARY KEY(CHAH_LOG_ID),
	CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

SELECT * FROM CHAT;
DELETE FROM CHAT;

INSERT(CHAH_LOG_ID, MEMBER_ID, CHAR_LOG_ANSWER, CHAH_LOG_CONTENT, 
		CHAR_LOG_DATE) 
INTO CHAT 
VALUES(1, 1, 'TEST_CHAR_LOG_ANSWER', 'TEST_CHAH_LOG_CONTENT', SYSDATE);