CREATE TABLE CONCERT(
	CONCERT_ID		NUMBER,
	CONCERT_NAME	VARCHAR2(20)	NOT NULL,
	CONCERT_DAY		DATE NOT NULL,
	CONCERT_MUSICIAN	VARCHAR2(20)	NOT NULL,
	CONCERT_OPEN	VARCHAR2(20)	NOT NULL,
	CONCERT_CLOSE	VARCHAR2(20)	NOT NULL,
	CONCERT_IMAGE	VARCHAR2(20),
	GENRE_ID		VARCHAR2(20)	NOT NULL,
	LOCAL_ID		VARCHAR2(20)	NOT NULL,
	CONCERT_PRICE	VARCHAR2(20)	NOT NULL,
	CONSTRAINT PRIMARY KEY(CONCERT_ID),
	CONSTRAINT FOREIGN KEY(GENRE_ID) REFERENCES GENRE(GENRE_ID),
	CONSTRAINT FOREIGN KEY(LOCAL_ID) REFERENCES LOCAL_INFO(LOCAL_ID)
);

SELECT * FROM CONCERT;
DELETE FROM CONCERT;

INSERT(CONCERT_ID, CONCERT_NAME, CONCERT_DAY, CONCERT_MUSICIAN, CONCERT_OPEN, 
		CONCERT_CLOSE, GENRE_ID, LOCAL_ID, CONCERT_PRICE) 
INTO CONCERT 
VALUES(
	1, '악동뮤지션 콘서트', SYSDATE, '악동뮤지션', '19시', '23시', 1, 1, '80000'
);

