CREATE TABLE GENRE(
	GENRE_ID	NUMBER
	GENRE_NAME	VARCHAR2(20)	NOT NULL,
	CONSTRAINT PRIMARY KEY(GENRE_ID)
);

SELECT * FROM GENRE;
DELETE FROM GENRE;

INSERT(GENRE_ID, GENRE_NAME) 
INTO GENRE 
VALUES(1, 'HIPHOP');