CREATE TABLE LIKEY(
	LIKEY_ID	NUMBER,
	CONCERT_ID	NUMBER	NOT NULL,
	MEMBER_ID	NUMBER	NOT NULL,
	CONSTRAINT PRIMARY KEY(LIKEY_ID)
);

SELECT * FROM LIKEY;
DELETE FROM LIKEY;

INSERT(LIKEY_ID, CONCERT_ID, MEMBER_ID) 
INTO LIKEY 
VALUES(1, 1, 1);