CREATE TABLE LOCAL_INFO(
	LOCAL_ID	NUMBER,
	LOCAL_NAME	VARCHAR2(20)	NOT NULL,
	CONSTRAINT PRIMARY KEY(LOCAL_ID)
);

SELECT * FROM LOCAL_INFO;
DELETE FROM LOCAL_INFO;

INSERT(LOCAL_ID, LOCAL_NAME) 
INTO LOCAL_INFO 
VALUES(1, '¼­¿ï');