CREATE TABLE RECENT_SEARCH(
	RECENT_SEARCH_ID		NUMBER,
	MEMBER_ID				VARCHAR2(20)	NOT NULL,
	RECENT_SEARCH_CONTENT	VARCHAR2(20)	NOT NULL,
	PRIMARY KEY(RECENT_SEARCH_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER
);
create sequence recent_seq increment by 1 start with 1;
SELECT * FROM RECENT_SEARCH;
DELETE FROM RECENT_SEARCH;

INSERT INTO RECENT_SEARCH VALUES(recent_seq.nextval, 'TEST_ID', 'TEST_RECENT_SEARCH_CONTENT');