CREATE TABLE RECENT_SEARCH(
	RECENT_SEARCH_ID		NUMBER,
	MEMBER_ID				VARCHAR2(20)	NOT NULL,
	RECENT_SEARCH_CONTENT	VARCHAR2(20)	NOT NULL,
	CONSTRAINT	PRIMARY KEY(RECENT_SEARCH_ID),
	CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

SELECT * FROM RECENT_SEARCH;
DELETE FROM RECENT_SEARCH;

INSERT(RECENT_SEARCH_ID, MEMBER_ID, RECENT_SEARCH_CONTENT) 
INTO RECENT_SEARCH 
VALUES(1, 'TEST_ID', 'TEST_RECENT_SEARCH_CONTENT');