CREATE TABLE REPLY(
	REPLY_ID	NUMBER,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	BOARD_ID	VARCHAR2(20)	NOT NULL,
	REPLY_CONTENT	VARCHAR2(20)	NOT NULL,
	PRIMARY KEY(REPLY_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER,
	FOREIGN KEY(BOARD_ID) REFERENCES BOARD
);

SELECT * FROM REPLY;
DELETE FROM REPLY;

INSERT INTO REPLY VALUES(1, 'TEST_ID', 'TEST_BOARD_ID', 'TEST_REPLY_CONTENT');