CREATE TABLE REPLY(
	REPLY_ID	NUMBER,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	BOARD_ID	VARCHAR2(20)	NOT NULL,
	REPLY_CONTENT	VARCHAR2(20)	NOT NULL,
	CONSTRAINT	PRIMARY KEY(REPLY_ID),
	CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	CONSTRAINT FOREIGN KEY(BOARD_ID) REFERENCES BOARD(BOARD_ID)
);

SELECT * FROM REPLY;
DELETE FROM REPLY;

INSERT(REPLY_ID, MEMBER_ID, BOARD_ID, REPLY_CONTENT) 
INTO REPLY 
VALUES(1, 'TEST_ID', 'TEST_BOARD_ID', 'TEST_REPLY_CONTENT');